### ISSUE TITLE
Change steps into actions and add a plan section

### ISSUE THREAD

**Issue by kostas-vl** [kostas-vl/bld#32]
In order to make sharing functionality between pipelines easier, there should be a way to define an action that is shared between pipelines. And so a pipeline file could be defined without a target (machine or docker image) and just contain actions to be shared by other pipelines e.g. 

```yaml
name: shared actions

actions:
- name: action_1
  exec:
  -  echo hello
```

```yaml
name: actual pipeline
runs-on: ubuntu

actions:
- name: print hello and do other stuff
  call:
  - bld:action:some_pipeline/shared.yaml(action_1)
  exec:
  - npm build 
```

This means that the steps section will be renamed to actions and also a way to define a set of action that should be executed by the pipeline is required. So a new section should be introduced called plan that would contain a list of action that would be executed on a pipeline run. The plan section should be optional and if it does not exist, all action in the pipeline will be executed.

```yaml
name: pipeline
runs-on: ubuntu

actions:
- name: fetch repository
  exec:
  - git clone ...
- name: build
  exec:
  - npm build

plan:
- fetch repository
- build
- bld:action:shared_pipelines/deploy.yaml(deploy to some remote server)
```
