### ISSUE TITLE
Add support for built in functions

### ISSUE THREAD

**Issue by kostas-vl** [kostas-vl/bld#62]
Bld should have a set of built in functions to provide future functionality inside sections of a pipeline.

Examples of such functions
- A function to store the result of an exec command inside a variable and use it on another.
- A function to parallelize mutliple exec commands

Example Syntax:

For function set
```yaml
name: pipeline
runs-on: ubuntu

steps:
- name: step 1
  exec:
  - bld:set(variable_name, echo hello world)

- name: step 2
  exec:
  - echo bld:var:variable_name
```

For function parallel
```yaml
name: pipeline
runs-on: ubuntu

steps:
- name: step 1
  exec:
  - bld:parallel(echo hello world, echo goodbye world)
```
