### ISSUE TITLE
Better support for docker images

### ISSUE THREAD

**Issue by kostas-vl** [kostas-vl/bld#84]
In the runs_on section the user should be able to configure the behavior for the image used. 

### Build a Dockerfile as part of the run.

The syntax could be something like
```yaml
runs_on:
    dockerfile: bld:root_dir/services/service_name/Dockerfile
    tag: my-service-image
    build: always
```

So from the above the user will be able to point to a Dockerfile, build it before each step is executed and give it a name. Also the build section could take values such as `always` to always execute before each run or `once` by checking if an image with the same name already exists.

### Pull image as part of the run

The syntax could be something like
```yaml
runs_on:
    image: ubuntu
    pull: true
```

And have the option to both define the image name and if the image should be pulled when the run starts.
