### ISSUE TITLE
Add jobs section

### ISSUE THREAD

**Issue by kostas-vl** [kostas-vl/bld#85]
Bld needs to be able to do parallel work as part of the run. To achieve this a new section that encapsulates the steps should be added that will execute in parallel a set of steps.

The syntax for this could be
```yaml
jobs:
    my-service-1:
        - name: Clone repository
          exec:
          - git clone ...
        
        - name: Build service 1
          exec:
          - ....
          - ...
        
    my-service-2:
        - name: Clone repository
          exec:
          - git clone ...
        
        - name: Build service 2
          exec:
          - ....
          - ...
```
